config/routes.rb
Rails.application.routes.draw do

  devise_for :users
  root 'vuelos#index'
  get 'vuelos/routes', to: 'vuelos#routes'
  get '/promo', to: 'vuelos#promo'
  post '/promo', to: 'vuelos#promo_create'
  get '/promo/:id', to: 'vuelos#edit_promo'
  get '/promo/:id', to: 'vuelos#edit_promo', as: 'edit_promo'
  put '/promo/:id', to: 'vuelos#update_promo'
  delete '/promo/:id', to: 'vuelos#destroy_promo'
  delete '/promo', to: 'vuelos#destroy_promo'
  resources :vuelos do 
    resources :checkouts
  end
end

app/models/ability.rb
class Ability
  include CanCan::Ability

  def initialize(user)
    # Define abilities for the passed in user here. For example:

      user ||= User.new # guest user (not logged in)
      if user.has_role? :admin
        can :manage, :all
      else
        can :read, :all
      end
    #
    # The first argument to `can` is the action you are giving the user 
    # permission to do.
    # If you pass :manage it will apply to every action. Other common actions
    # here are :read, :create, :update and :destroy.
    #
    # The second argument is the resource the user can perform the action on. 
    # If you pass :all it will apply to every resource. Otherwise pass a Ruby
    # class of the resource.
    #
    # The third argument is an optional hash of conditions to further filter the
    # objects.
    # For example, here the user can only update published articles.
    #
    #   can :update, Article, :published => true
    #
    # See the wiki for details:
    # https://github.com/ryanb/cancan/wiki/Defining-Abilities
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/promo.rb
class Promo < ApplicationRecord
   mount_uploader :image, AvatarUploader
end

app/models/role.rb
class Role < ApplicationRecord
has_and_belongs_to_many :users, :join_table => :users_roles


belongs_to :resource,
           :polymorphic => true,
           :optional => true


validates :resource_type,
          :inclusion => { :in => Rolify.resource_types },
          :allow_nil => true

scopify
end

app/models/user.rb
class User < ApplicationRecord
  rolify
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :user_flies
  has_many :vuelos, through: :user_flies
  mount_uploader :avatar, AvatarUploader
end

app/models/user_fly.rb
class UserFly < ApplicationRecord
  belongs_to :user
  belongs_to :vuelo
  
end

app/models/vuelo.rb
class Vuelo < ApplicationRecord
  has_many :user_flies
  has_many :users, through: :user_flies
  resourcify
  
  def self.search(search)
    if search
      vuelo = Vuelo.find_by(departure: search[:departure]) && Vuelo.find_by(destination: search[:destination])
    else
      Vuelo.all
    end
  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base

  protect_from_forgery with: :exception

  before_action :configure_permitted_parameters, if: :devise_controller?

  protected

        def configure_permitted_parameters
            devise_parameter_sanitizer.permit(:sign_up) { |u| u.permit(:avatar, :name, :last_name, :email, :password) }
            devise_parameter_sanitizer.permit(:account_update) { |u| u.permit(:avatar, :name, :last_name, :email, :password, :current_password) }
        end
end

app/controllers/checkouts_controller.rb
class CheckoutsController < ApplicationController
  before_action :set_passenger, only: [:index, :new, :create]
  before_action :find_fly, only: [:index, :new, :create]

  def index
  end

  def show
  end

  def new
  end
  
  def create
    @link = @vuelo.user_flies.create(user_id: current_user.id)
    if @link
      redirect_to vuelo_checkouts_path(people: @people), notice: "Vuelo confirmado"
    end
  end
  
  private
  def set_passenger
    @people = params[:people]
  end
  
  def find_fly
    @vuelo = Vuelo.find_by(id: params[:vuelo_id])
    end
end

app/controllers/vuelos_controller.rb
class VuelosController < ApplicationController
  before_action :set_passsanger, only: [:show, :index, :routes]
  before_action :set_vuelo, only: [:show, :edit, :update, :destroy]
  before_action :set_promo, only: [:edit_promo, :update_promo, :destroy_promo]

  def index
      @vuelo = Vuelo.search(vuelo_params)
      @promos = Promo.all
    end
    
    def show
    end
    
    def new
      @vuelo = Vuelo.new
    end
    
    def create
      @vuelo = Vuelo.create(vuelo_create_params)
      if @vuelo
        redirect_to vuelos_routes_path, notice: "Vuelo creado"
      else
        render 'new', alert: "Hubo un error, intentalo de nuevo"
      end
    end
    
    def edit
    end
    
    def update
      if @vuelo.update(vuelo_create_params)
        redirect_to vuelos_routes_path, notice: "Vuelo Actualizado"
      else
        redirect_to edit_vuelo_path, alert: "Ooh! Hubo un error"
      end
    end

    def destroy
      if @vuelo.destroy
        redirect_to vuelos_routes_path, notice: "Vuelo Borrado"
      end
    end

    def routes
      set_vuelos
    end
    
    def promo
      set_vuelos
      @promo = Promo.new
    end

    def promo_create
      @promo = Promo.create(promo_params)
      if @promo
        redirect_to root_path, notice: "Promocion creada"
      else
        redirect_to vuelos_promo_path, alert: "Hubo un error, intentalo de nuevo"
      end
    end
    
    def edit_promo
      set_vuelos
    end
    
    def update_promo
      if @promo.update(promo_params)
        redirect_to root_path, notice: "Promocion Actualizada"
      else
        redirect_to vuelos_promo_path, alert: "Hubo un error, intentalo de nuevo"
      end
    end
    
    def destroy_promo
      if @promo.destroy
        redirect_to root_path, notice: "Promocion Borrada"
      else
        redirect_to root_path, alert: "Ooh! Hubo un error"
      end
    end
    
    private
      def set_vuelos
        @vuelos = Vuelo.all
      end

      def set_promo
        @promo = Promo.find_by(id: params[:id])
      end

      def set_vuelo
        @vuelo = Vuelo.find_by(id: params[:id])
      end

      def promo_params
        params.require(:promo).permit(:image, :description_package, :description, :description_value, :price_promo, :vuelo_id)
      end
      
      def vuelo_create_params
        params.require(:vuelo).permit(:departure, :destination, :passenger, :price)
      end

      def vuelo_params
        params.permit(:departure, :destination, :passenger, :people)
      end
      
      def set_passsanger
        @people = params[:people]
      end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/checkouts_helper.rb
module CheckoutsHelper
end

app/helpers/vuelos_helper.rb
module VuelosHelper
end

app/views/checkouts/index.html.erb
<div class="container">
  <div class="title text-center">
    <h1>CHECKOUT</h1>
  </div>

  <div class="checkout__container">
    <div class="checkout__box">
      <div class="checkout__details">

        <p class="checkout__details--description">
          <em>Estos son los datos de tu vuelo: </em>
        </p>

        <div class="checkout__details--fly">
          <div class="departure">
            <span>Origen: </span>
            <%= @vuelo.departure%>
          </div>
          <div class="destination">
            <span>Destino: </span>
            <%= @vuelo.destination %>
          </div>
        </div>

        <div class="checkout__details--checkbox mt-1">
          <em>Ida y Vuelta</em>
          <%= check_box_tag 'Ida y Vuelta',  nil, true %>
        </div>

        <div class="checkout__details--user mt-2">
          <div class="name">
            <span>Nombre: </span>
            <%= current_user.name%>
          </div>
          <div class="last_name">
            <span>Apellidos: </span>
            <%= current_user.last_name%>
          </div>
        </div>

        <div class="checkout__details--data">
          <div class="email">
            <span>Correo: </span>
            <%= current_user.email%>
          </div>
          <div class="passengers">
            <span>Nº Pasajeros: </span>
            <%= @people %>
          </div>
        </div>

      </div>
    </div>
  </div>
</div>

app/views/checkouts/new.html.erb
<div class="container">
  <div class="title text-center">
    <h1>CHECKOUT</h1>
  </div>

  <div class="checkout__container">
    <div class="checkout__box">
      <div class="checkout__details">

        <p class="checkout__details--description">
          <em>Estos son los datos de tu vuelo, por favor confirma y presionas ACEPTAR si estas de acuerdo</em>
        </p>

        <div class="checkout__details--fly">
          <div class="departure">
            <span>Origen: </span>
            <%= @vuelo.departure%>
          </div>
          <div class="destination">
            <span>Destino: </span>
            <%= @vuelo.destination %>
          </div>
        </div>

        <div class="checkout__details--checkbox">
          <em>Ida y Vuelta</em>
          <%= check_box_tag 'Ida y Vuelta',  nil, true %>
        </div>

        <div class="checkout__details--user">
          <div class="name">
            <span>Nombre: </span>
            <%= current_user.name%>
          </div>
          <div class="last_name">
            <span>Apellidos: </span>
            <%= current_user.last_name%>
          </div>
        </div>

        <div class="checkout__details--data">
          <div class="email">
            <span>Correo: </span>
            <%= current_user.email%>
          </div>
          <div class="passengers">
            <span>Nº Pasajeros: </span>
            <%= @people %>
          </div>
        </div>

        <div class="checkout_buttons mt-2">
          <div class="agree">
            <%= link_to "ACEPTO", vuelo_checkouts_path(people: @people), method: :post, class:"btn btn-outline-success btn-lg btn-animation" %>
          </div>
          <div class="refuse">
            <%= link_to "RECHAZO", root_path, class:"btn btn-lg btn-outline-danger btn-animation", notice: "Vuelo Cancelado" %>
          </div>
        </div>

      </div>
    </div>
  </div>
</div>

app/views/checkouts/show.html.erb
<h1>Checkouts#show</h1>
<p>Find me in app/views/checkouts/show.html.erb</p>

app/views/layouts/_footer.html.erb
<div class="footer p-5">
  <div class="container">

    <div class="contacto">
      <div class="redes">
          <%=icon('fab', 'facebook-square m-2')%>
          <%=icon('fab', 'twitter m-2')%>
          <%=icon('fab', 'instagram m-2')%>
          <%=icon('fab', 'youtube m-2')%>
      </div>
      <div class="numeros">
        <div class="numeros_1">
          <span class="bold">Para ventas</span>
          01-8000-0000
        </div>
        <div class="numeros_2">
          <span class="bold">Posventa</span>
          +57 0000 00 00
        </div>
      </div>
    </div>
    <hr/>

    <div class="footer_description">
      <div class="nosotros">
        <span class="header">Somos despegando</span>
        <ul class= "list">
          <li class="list_item">Nuestro telefono</li>
          <li class="list_item">Ven a trabajar a despegando</li>
          <li class="list_item">Relacion con inversores</li>
          <li class="list_item">Sobre despegando</li>
        </ul>
      </div>
      <div class="terminos">
        <span class="header">Confianza en tus compras</span>
        <ul class= "list">
          <li class="list_item">Terminos y condiciones</li>
          <li class="list_item">Politica de privacidad</li>
        </ul>
      </div>
      <div class="negocio">
        <span class="header">Potencia tu negocio</span>
        <ul class= "list">
          <li class="list_item">Agrega tu flota</li>
          <li class="list_item">Programa de Agencias Afiliadas</li>
          <li class="list_item">Se parte de la red Afiliados</li>
          <li class="list_item">¿Viajas por negocio?</li>
        </ul>
      </div>
    </div>
  </div>
</div>

app/views/layouts/_navbar.html.erb
<nav class="header-container nav">
  <div class="header-logo nav-item">
     <%=icon('fas', 'plane')%>
    <%= link_to "despegando", root_path, class: "nav-link"%>
  </div>

  <ul class="header-sesion nav ">
    <div class="nav-item">
     <%=icon('fas', 'user')%>
     <% if user_signed_in? %>
      <%= link_to "Logout", destroy_user_session_path, method: :delete%>
     <% else %>
      <%= link_to "Iniciar sesion", user_session_path%>
     <% end %>
    </div>
    <div class="nav-item">
     <% if user_signed_in? %>
        <%=icon('fas', 'user-edit')%>
        <%= link_to "Edit", edit_user_registration_path %>
     <% end %>
    </div>
    <div class="nav-item">
      <%=icon('fas', 'suitcase-rolling')%>
      <%= link_to "Rutas", vuelos_routes_path%>
    </div>
    <% if user_signed_in? %>
      <% if current_user.has_role? :admin %>
      <div class="nav-item">
        <%=icon('fab', 'fly')%>
        <%= link_to "Promo", promo_path%>
      </div>
      <% end %>
    <% end %>
    <div class="nav-item">
      <%=icon('fas', 'question-circle')%>
      <%= link_to "Ayuda"%>
    </div>
  </ul>
</nav>

<div class="header-navigation">
  <div class="header-products">
    <ul class="header-products--list">
      <li class="header-products--item">
        <%=icon('fas', 'bed')%>
        <%= link_to "Alojamiento", vuelos_path, class: "nav-link"%>
      </li>
      <li class="header-products--item">
        <%=icon('fas', 'plane-departure')%>
        <%= link_to "Paquetes", vuelos_path, class: "nav-link"%>
      </li>
      <li class="header-products--item">
        <%=icon('fas', 'suitcase')%>
        <%= link_to "Imbatibles", vuelos_path, class: "nav-link"%>
      </li>
      <li class="header-products--item">
        <%=icon('fas', 'running')%>
        <%= link_to "Escapadas", vuelos_path, class: "nav-link"%>
      </li>
      <li class="header-products--item">
        <%=icon('fas', 'ticket-alt')%>
        <%= link_to "Actividades", vuelos_path, class: "nav-link"%>
      </li>
      <li class="header-products--item">
        <%=icon('fas', 'medkit')%>
        <%= link_to "Seguros", vuelos_path, class: "nav-link"%>
      </li>
    </ul>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Despegando</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <% if notice %><p class="notice" id="notice"><%= notice %></p><% end %>
    <% if alert %><p class="alert" id="alert"><%= alert %></p><% end %>
    <%if current_page?(user_session_path) || current_page?(new_user_registration_path) %>
      <%= yield %>
    <% else %>
      <%= render "layouts/navbar" %>
      <%= yield %>
    <% end %>
  </body>
</html>

app/views/vuelos/edit.html.erb
<div class="container">
  <h1 class="text-center">Editar Vuelo</h1>

  <div class="form_create-fly">
    <%= form_with model: @vuelo, class: "form" do |vuelo| %>
      <p>Ingresa los datos del vuelo: </p>
      <div class="form--departure mb-2">
        <%= vuelo.text_field :departure, placeholder: "Origen", class: "input" %>
      </div>
      <div class="form--destination mb-2">
        <%= vuelo.text_field :destination, placeholder: "Destino", class: "input" %>
      </div>
      <div class="form--passenger mb-2">
        <%= vuelo.text_field :passenger, placeholder: "Capacidad de pasajeros", class: "input" %>
      </div>
      <div class="form--price mb-2">
        <%= vuelo.text_field :price, placeholder: "Precio unitario", class: "input" %>
      </div>
      <%= vuelo.submit "Actualizar vuelo", class: "btn btn-lg btn-default mt-3" %>
    <% end %>
  </div>

</div>

app/views/vuelos/edit_promo.html.erb
<div class="container">
  <h1 class="text-center">Editar promocion</h1>

  <div class="form_create-promo">
    <%= form_with url: "/promo/#{@promo.id}", scope: 'promo', method: :put,  class: "form" do |promo| %>
      <p>Ingresa los datos de la promocion: </p>
      <div class="form--image mb-2">
        <%= promo.file_field :image%>
      </div>
      <div class="form--departure mb-2">
        <%= promo.text_field :description_package, placeholder: "Descripcion del paquete", class: "input" %>
      </div>
      <div class="form--destination mb-2">
        <%= promo.text_field :description, placeholder: "descripcion general", class: "input" %>
      </div>
      <div class="form--passenger mb-2">
        <%= promo.text_field :description_value, placeholder: "Decripcion del valor", class: "input" %>
      </div>
      <div class="form--price mb-2">
        <%= promo.text_field :price_promo, placeholder: "Precio de la promo", class: "input" %>
      </div>
      <div class="form--vuelos mb-2">
        <em>Selecciona el vuelo al cual va a estar vinculado la promocion (destino)</em>
        <%= promo.collection_select :vuelo_id, @vuelos, :id, :destination, {prompt: "Selecciona el destino"},  class: "input" %>
      </div>
      <%= promo.submit "Actualizar promo", class: "btn btn-lg btn-default mt-3" %>
    <% end %>
  </div>

</div>

app/views/vuelos/index.html.erb
<div class="home-container">
  <div class="searchbox p-3">
    <div class="box">
      <!--box header -->
      <div class="box-header">
        <div class="box-header--title">
          <h2>Vuelos baratos</h2>
        </div>
      </div>
      <!--box row -->
      <div class="box-row row">

        <!--box-row--inputs -->
        <div class="box-row--inputs col-7 row">
          <%= form_tag(vuelos_path, method: :get, class: "row")  do %>
          <div class="box-row--input col-6">
            <%= label_tag(:departure, 'Origen') %>
            <%= text_field_tag :departure, nil, placeholder: "Ingresa desde donde viajas" %>
          </div>
          <div class="box-row--input col-6">
            <%= label_tag(:destination, 'Destino') %>
            <%= text_field_tag :destination, nil, placeholder: "Ingresa hacia donde viajas" %>
          </div>
        </div>

        <!--box-row--passenger -->
        <div class="box-row--passenger col-3">
          <div class="box-row--container">
            <%= label_tag(:people, 'Pasajeros')%>
            <div class="box-row--input">
              <%= text_field_tag :people,  nil, placeholder: "personas"  %>
            </div>
          </div>
        </div>

        <!--box-row--button -->
        <div class="box-row--button col-2">
          <div class="box-row--button--container">
            <%= submit_tag('Buscar',name: nil,class: "btn btn-lg btn-animation") %>
          </div>
        </div>
          <% end  %>
      </div>
    </div>
  </div>
</div>

<!-- Resultado de la busqueda -->
<% if @vuelo  %>
<div class="container mt-5">
  <div class="show-flights p-2 row">
    <div class="show-flights--group-1 col-9 row justify-content-center">
      <div class="show-flights__departure ml-5 mr-5">
        <%= @vuelo.departure%>
      </div>
      <div class="to m-2">
          <%=icon('fas', 'long-arrow-alt-right')%>
      </div>
      <div class="show-flights__destination ml-5 mr-5">
        <%= @vuelo.destination%>
      </div>
    </div>
    <div class="show-flights--group-2 col-3 row justify-content-center">
      <div class="show-flights--selection m-2">
        <%= link_to 'Seleccionar', vuelo_path(@vuelo, people: @people), class: "btn btn-lg btn-default btn-animation" %>
      </div>
    </div>
  </div>
</div>
<% end %>

<!-- Promociones de vuelos -->
<% if @promos  %>
<div class="container">
  
  <div class="Promociones mt-5">
    <div class="promociones__title">
      <h2>Promociones</h2>
    </div>

    <div class="promociones__container mb-5 row">
          <% @promos.each do |promo|%>

            

            <% if user_signed_in? %>

              <% if current_user.has_role? :admin %>
                <div class="card card-admin" style="width: 18rem;">
                <%= link_to vuelo_path(promo.vuelo_id.to_s, people: 1) do%>
                  <%= image_tag(promo.image_url(:photo).to_s, class: "card-img-top")%>
                <% end %>

                <div class="card-body">
                  <h6 class="card-title">
                    <div class="text_package">
                      <%= promo.description_package %>
                    </div>
                  </h6>
                  <h4 class="card-title">
                    <%= promo.description %>
                  </h4>
                </div>

                <div class="card-body field-price">
                  <div class="field-price">
                    <em class="text_price">
                      <%= promo.description_value %>
                    </em>
                    <span class="value_price text-right">
                      $<%= promo.price_promo %>
                    </span>
                  </div>
                  <div class="text-center mt-1">
                    <%= link_to "Editar", edit_promo_path(id: promo.id), class: "btn btn-outline-warning" %>
                    <%= link_to "Borrar", promo_path(id: promo.id), class: "btn btn-outline-danger", method: :delete %>
                  </div>
                </div>
                
                </div>
              <% else %>

                <%= link_to vuelo_path(promo.vuelo_id, people: 1), class: "link-card" do%>
                  <div class="card" style="width: 18rem;">
                    <%= image_tag(promo.image_url(:photo).to_s, class: "card-img-top")%>

                    <div class="card-body">
                      <h6 class="card-title">
                        <div class="text_package">
                          <%= promo.description_package %>
                        </div>
                      </h6>
                      <h4 class="card-title">
                        <%= promo.description %>
                      </h4>
                    </div>

                    <div class="card-body field-price">
                      <em class="text_price">
                        <%= promo.description_value %>
                      </em>
                      <span class="value_price">
                        $<%= promo.price_promo %>
                      </span>
                    </div>
                    

                  </div>
                <% end %>

              <% end %>

            <% else %>
            
              <%= link_to vuelo_path(promo.vuelo_id, people: 1), class: "link-card" do%>
                <div class="card" style="width: 18rem;">
                  <%= image_tag(promo.image_url(:photo).to_s, class: "card-img-top")%>

                  <div class="card-body">
                    <h6 class="card-title">
                      <div class="text_package">
                        <%= promo.description_package %>
                      </div>
                    </h6>
                    <h4 class="card-title">
                      <%= promo.description %>
                    </h4>
                  </div>

                  <div class="card-body field-price">
                    <em class="text_price">
                      <%= promo.description_value %>
                    </em>
                    <span class="value_price">
                      $<%= promo.price_promo %>
                    </span>
                  </div>
                  

                </div>
              <% end %>

            <% end %>

          <% end %>
    </div>

  </div>

</div>
<% end %>


<%= render "layouts/footer" %>

app/views/vuelos/new.html.erb
<div class="container">
  <h1 class="text-center">Nuevo Vuelo</h1>

  <div class="form_create-fly">
    <%= form_with model: @vuelo, class: "form" do |vuelo| %>
      <p>Ingresa los datos del vuelo: </p>
      <div class="form--departure mb-2">
        <%= vuelo.text_field :departure, placeholder: "Origen", class: "input" %>
      </div>
      <div class="form--destination mb-2">
        <%= vuelo.text_field :destination, placeholder: "Destino", class: "input" %>
      </div>
      <div class="form--passenger mb-2">
        <%= vuelo.text_field :passenger, placeholder: "Capacidad de pasajeros", class: "input" %>
      </div>
      <div class="form--price mb-2">
        <%= vuelo.text_field :price, placeholder: "Precio unitario", class: "input" %>
      </div>
      <%= vuelo.submit "Crear vuelo", class: "btn btn-lg btn-default mt-3" %>
    <% end %>
  </div>

</div>

app/views/vuelos/promo.html.erb
<div class="container">
  <h1 class="text-center">Crear promocion</h1>

  <div class="form_create-promo">
    <%= form_with url: '/promo', scope: 'promo', method: :post,  class: "form" do |promo| %>
      <p>Ingresa los datos de la promocion: </p>
      <div class="form--image mb-2">
        <%= promo.file_field :image%>
      </div>
      <div class="form--departure mb-2">
        <%= promo.text_field :description_package, placeholder: "Descripcion del paquete", class: "input" %>
      </div>
      <div class="form--destination mb-2">
        <%= promo.text_field :description, placeholder: "descripcion general", class: "input" %>
      </div>
      <div class="form--passenger mb-2">
        <%= promo.text_field :description_value, placeholder: "Decripcion del valor", class: "input" %>
      </div>
      <div class="form--price mb-2">
        <%= promo.text_field :price_promo, placeholder: "Precio de la promo", class: "input" %>
      </div>
      <div class="form--vuelos mb-2">
        <em>Selecciona el vuelo al cual va a estar vinculado la promocion (destino)</em>
        <%= promo.collection_select :vuelo_id, @vuelos, :id, :destination, {prompt: 'Selecciona el destino'}, class: "input" %>
      </div>
      <%= promo.submit "Crear promo", method: :post, class: "btn btn-lg btn-default mt-3 btn-animation" %>
    <% end %>
  </div>

</div>

app/views/vuelos/routes.html.erb
<div class="container">

  <% if @vuelos  %>
    <% @vuelos.each do |vuelo|%>
      <div class="container mt-5 mb-5">
        <div class="show-flights p-2 row">
          <div class="show-flights--group-1 col-9 row justify-content-center">
            <div class="show-flights__departure ml-5 mr-5">
              <%= vuelo.departure%>
            </div>
            <div class="to m-2">
                <%=icon('fas', 'long-arrow-alt-right')%>
            </div>
            <div class="show-flights__destination ml-5 mr-5">
              <%= vuelo.destination%>
            </div>
          </div>
          <div class="show-flights--group-2 col-3 row justify-content-center">
            <div class="show-flights--selection m-2">
              <% if user_signed_in? %>
                <% if current_user.has_role? :admin %>
                  <%= link_to 'Editar', edit_vuelo_path(id: vuelo.id), class: "btn btn-lg btn-outline-warning" %>
                  <%= link_to 'Borrar', vuelo_path(vuelo.id), method: :delete, class: "btn btn-lg btn-outline-danger" %>
                <% else %>
                  <%= link_to 'Seleccionar', vuelo_path(vuelo.id, people: @people), class: "btn btn-lg btn-default" %>
                <% end %>
              <% end %>
            </div>
          </div>
        </div>
      </div>
    <% end %>
  <% end %>

  <% if user_signed_in? %>
    <% if current_user.has_role? :admin %>
      <div class="create-new-route mb-4">
        <%= link_to 'Crear nueva ruta', new_vuelo_path, class: "btn btn-lg btn-default" %>
      </div>
    <% end %>
  <% end %>

</div>

app/views/vuelos/show.html.erb
<div class="show">
  <div class="container">
    <div class="card card-vuelo">
        <div class="card-body--division title">
          <div class="title">
            <h5>Disfruta de tu viaje a <%= @vuelo.destination%></h5>
          </div>
        </div>
        <div class="card-body--division departure">
          <div class="box row">
            <p>Ida</p>
            <%=icon('fas', 'plane-departure')%>
          </div>
          <h6 class="card-title text-center p-4 row">
            <%= @vuelo.departure%> - <%= @vuelo.destination%>
          </h6>
        </div>
        <div class="card-body--division destination">
          <div class="box row">
            <p>Vuelta</p>
            <%=icon('fas', 'plane-arrival')%>
          </div>
          <h6 class="card-title text-center p-4 row">
            <%= @vuelo.destination%> - <%= @vuelo.departure%>
          </h6>
        </div>
        <div class="card-body--division selection">
          <div class="prices">

            <div class="price_main mb-2 text-right">
              <div class="price_main--title">
                <span>Precio por adulto</span>
              </div>
              <div class="price_main--amount">
                <span>$<%= @vuelo.price %></span>
              </div>
            </div>

            <div class="price_details">
              <div class="price_details--items">
                <div class="price_details--item">
                  <p class="price_details--subitems">
                  <em><%= @people %> Adulto</em>
                  <span>
                    <% pr = @vuelo.price * @people.to_i %>
                    <% imp =  pr * 0.19  %>
                    <% car = pr  / 6.6 %>
                    $<%= pr.round(2) - (imp.round(2) + car.round(2)) %>
                  </span>
                  </p>
                  <p class="price_details--subitems">
                  <em>Imp. y tasas</em>
                  <span>
                    $<%= imp.round(2) %>
                  </span>
                  </p>
                  <p class="price_details--subitems">
                  <em>Cargos</em>
                  <span>
                    $<%= car.round(2) %>
                  </span>
                  </p>
                  <hr/>
                  <p class="price_details--subitems final">
                  <em>Precio final</em>
                  <span>
                    $<%= @vuelo.price * @people.to_i %>
                  </span>
                  </p>
                </div>
              </div>
            </div>

            <div class="price_button text-center">
              <% if  user_signed_in? %>
                <%= link_to 'Seleccionar', new_vuelo_checkout_path(@vuelo, people: @people), class: "btn btn-lg"  %>
              <% else %>
                <%= link_to 'Seleccionar', user_session_path, class: "btn btn-lg" %>
              <% end %>
            </div>
          </div>
        </div>
    </div>
  </div>
</div>